# Generated by Django 3.1.4 on 2020-12-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_menber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menber',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='menber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sns.menber'),
        ),
    ]
