# Generated by Django 3.1.4 on 2020-12-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_auto_20201217_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menber',
            name='name',
            field=models.TextField(max_length=10),
        ),
    ]
