# Generated by Django 3.1.4 on 2020-12-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_auto_20201217_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='menberlist',
        ),
    ]
