# Generated by Django 3.1.4 on 2020-12-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0008_remove_message_menberlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='star',
            field=models.TextField(blank=True, choices=[('5', '5つ'), ('4', '4つ'), ('3', '3つ'), ('2', '2つ'), ('1', '1つ')], verbose_name='乃木星'),
        ),
    ]
