# Generated by Django 3.1.4 on 2020-12-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0010_auto_20201221_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='star',
            field=models.IntegerField(blank=True, choices=[('5', 5), ('4', 4), ('3', 3), ('2', 2), ('1', 1)], verbose_name='乃木星'),
        ),
    ]
